### ISSUE TITLE
not compatible with io.js - old jsdom depends on contextify

### ISSUE THREAD

**Issue by jden** [neocotic/html.md#50]
ref https://github.com/iojs/io.js/issues/456#issuecomment-74723983

see https://github.com/tmpvar/jsdom/commit/68356e154ad3844e9762daff5e0aa9c4e190f435 and https://github.com/brianmcd/contextify/issues/149

**Comment by neocotic** [comment]
I'm not sure I understand the issue. Can you please expand on exactly what the problem is and what needs fixed?

From what I just read it seems that the author of jsdom has just fallen out with nodejs, somewhat naively, claiming that nodejs is dead and doesn't contain his fix. 0.12 is out now so if his fix was in 0.11 it should be in the latest stable release of nodejs.

**Comment by jden** [comment]
> Can you please expand on exactly what the problem is and what needs fixed?

Sure :) The version of `jsdom` used by the latest version of `html-md` depends on `contextify`, a native module which does not compile against node 0.12.x or io.js 1.x. I am interested in migrating to io.js, so I checked my project deps using the list from https://github.com/iojs/io.js/issues/456 - I opened this issue as a tracking issue for if and when html-md is made io.js compatible.
