### ISSUE TITLE
Error: Cannot find module 'canvas'

### ISSUE THREAD

**Issue by felarof99** [neocotic/html.md#52]
I'm using version 3.0.2 of html-md and i'm getting the below error when I require html-md in my project.
npm version: 3.3.7
node version: v0.12.7

Error: Cannot find module 'canvas' from '..../node_modules/html-md/node_modules/jsdom/lib/jsdom/level2'

**Comment by neocotic** [comment]
Unfortunately, we're quite far behind the latest version of jsdom right now. I'm considering bumping the version, however, I'm also trying to consider possible more lightweight alternatives as jsdom still feels a bit overkill.

It appears that jsdom is requiring the "canvas" module in some places even though it's not listed as dependency (optional or otherwise). I've had a quick look at the jsdom source code for v0.8.11 (the most likely version you'll have installed based on our `~0.8.6` semver range used in the dependency) and the only place I can see where it attempts to require the "canvas" module is [here](https://github.com/tmpvar/jsdom/blob/0.8.11/lib/jsdom/level2/html.js#L1208):

``` javascript
try {
  var canvas = new (require('canvas'))(0,0);
  for (var attr in element) {
    if (!canvas[attr]) {
      canvas[attr] = element[attr];
    }
  }
  return canvas;
} catch (e) {
  return element;
}
```

Without knowing exactly what line your error is being thrown at, I can't really help further investigate why this is happening, especially when the above code appears to wrap the require in a try/catch block, which I would have expected to prevent your error from occurring.

It's also worth noting that this should only happen if you're attempting to use html.md with HTML containing an HTML5 `<canvas>` element. [According the the documentation](https://github.com/tmpvar/jsdom/tree/0.8.11#canvas) for that version of jsdom:

> jsdom includes support for using the [canvas](https://npmjs.org/package/canvas) package to extend any `<canvas>` elements with the canvas API. To make this work, you need to include canvas as a dependency in your project, as a peer of jsdom. If jsdom can find the canvas package, it will use it, but if it's not present, then `<canvas>` elements will behave like `<div>`s.

I think that this would be your best course of action. I'm still not sure why you're seeing this error though and it's not gracefully ignoring the "canvas" module as documented and as the code would suggest it does.

However, be aware that depending on the "canvas" module also requires your package to have other external dependencies. Make sure that you [read their wiki](https://github.com/Automattic/node-canvas/wiki) for complete installation instructions. This is probably why it's not a core dependency of jsdom.

I'm not convinced that a jsdom dependency bump for html.md would even fix this problem as it appears that it still does a similar check for the "canvas" module.
